httpAddr: "0.0.0.0:8080" # 查看模拟连接情况

server:
  addr: "0.0.0.0:808" # 服务端地址

client:
  ip: "127.0.0.1" # 客户端ip
  intervalMicrosecond: 1000 # 多久生成一个新客户端 默认1毫秒一个
  sum: 1000 # 测试的客户端总数
  sim: 1 # 初始的sim卡号 后面的就一直+1
  version: 2013 # 客户端版本 2013 2019
  commands: # 按周期循环的指令
    # 支持的指令 https://github.com/cuteLittleDevil/go-jt808?tab=readme-ov-file#jt808%E7%BB%88%E7%AB%AF%E9%80%9A%E8%AE%AF%E5%8D%8F%E8%AE%AE
    - name: 0x0200 #位置信息
      enable: true # 是否启用
      intervalSecond: 5 # 5秒钟发送一次
      sum: 1000 # 一共发送多少次 到了sum后就不发了 0不限制
    - name: 0x0002 #心跳
      enable: true
      intervalSecond: 30
      sum: 0
    - name: 0x0704 #批量位置 (默认实际里面就1个位置)
      enable: true
      intervalSecond: 60
      sum: 100